services:
  pod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPOSITORY=${REPOSITORY}
        - BRANCH=${BRANCH}
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file:
      - .env