services:
  # PostgreSQL database with pgvector extension
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: cage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cage API service
  api:
    build:
      context: .
      dockerfile: dockerfiles/api
      args:
        GIT_EMAIL: ${GIT_EMAIL:-cage-agent@example.com}
        GIT_NAME: ${GIT_NAME:-"Cage Agent"}
    command: ["python", "-m", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"  # Different port to avoid conflict
      - "5678:5678"  # debugpy debug port
    environment:
      - POD_TOKEN=${POD_TOKEN}
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cage
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPO_PATH=/work/repo
      - DEBUGPY_ENABLED=${DEBUGPY_ENABLED:-0}
      - DEBUGPY_WAIT_FOR_CLIENT=${DEBUGPY_WAIT_FOR_CLIENT:-0}
    volumes:
      - .:/app
      - ${REPO_PATH}:/work/repo
    depends_on:
      postgres: 
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  # MCP Server (Streamable HTTP)
  mcp:
    build:
      context: .
      dockerfile: dockerfiles/mcp
    command: ["python", "-m", "src.cage.mcp_server", "--host", "0.0.0.0", "--port", "8765"]
    ports:
      - "${MCP_PORT:-8765}:8765"
      - "5679:5679"  # debugpy debug port
    environment:
      - POD_TOKEN=${POD_TOKEN:-test-mcp-token}
      - MCP_TOKENS=${MCP_TOKENS:-test-mcp-token}
      - MCP_SESSION_TTL=${MCP_SESSION_TTL:-3600}
      - MCP_RATE_MAX_CALLS=${MCP_RATE_MAX_CALLS:-240}
      - DEBUGPY_ENABLED=${DEBUGPY_ENABLED:-0}
      - DEBUGPY_WAIT_FOR_CLIENT=${DEBUGPY_WAIT_FOR_CLIENT:-0}
    volumes:
      - .:/app
      - ${REPO_PATH}:/work/repo
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -X POST http://localhost:8765/mcp -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d '{\"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"tools/list\"}' --max-time 10 --write-out '%{http_code}' --output /dev/null --silent | grep -q '400'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Logging Stack - Loki (Log Aggregation)
  loki:
    image: grafana/loki:2.9.6
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./logging-stack/loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki
    ports:
      - '3100:3100'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3100/ready']
      interval: 15s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  # Logging Stack - Promtail (Log Collection)
  promtail:
    image: grafana/promtail:2.9.6
    volumes:
      - ./logging-stack/promtail/config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log/cage:ro
      - promtail-positions:/tmp
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped

  # Logging Stack - Grafana (Log Visualization)
  grafana:
    image: grafana/grafana:11.1.3
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped

  # Logging Stack - Logrotate (Log Rotation)
  logrotate:
    build:
      context: ./logging-stack/logrotate
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/log/cage
      - logrotate-status:/var/lib/logrotate
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  # Logging stack volumes
  loki-data:
  promtail-positions:
  grafana-data:
  logrotate-status:
