version: '3.8'

services:
  cursor-agent:
    build:
      context: ../..
      dockerfile: .scatchpad/cli-container/Dockerfile
    container_name: cursor-debug-container
    volumes:
      # Mount test file
      - ./test.txt:/app/test.txt:ro
      # Optional: Mount current directory for development
      - ./:/workspace:ro
    environment:
      # Set your Cursor API key here or via .env file
      - CURSOR_API_KEY=key_b4ef63a735ed5b4732484dd3b063bb0e789bbd1a2690d72e95ae5a685f1ac805
      # Optional: Set other environment variables
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    # Override default entrypoint to keep container running
    command: tail -f /dev/null
    # Alternatively, you can run the cursor-agent directly:
    # command: cursor-agent -p "What is the answer to the question in /app/test.txt?"
    
    # Optional: Expose port if you plan to run web services
    # ports:
    #   - "8080:8080"
    
    # Optional: Add network for multi-container setup
    # networks:
    #   - cursor-network
    
    # Optional: Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #       cpus: '1.0'

# Optional: Define custom network
# networks:
#   cursor-network:
#     driver: bridge