server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # API logs
  - job_name: cage-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          component: api
          __path__: /var/log/cage/api.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            file: file
            line: line
            event: event
            method: method
            url: url
            path: path
            status_code: status_code
            duration_ms: duration_ms
            client_ip: client_ip
      - labels:
          level:
          file:
          event:
          method:
          status_code:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
          action_on_failure: fudge
      - output:
          source: message

  # CrewAI logs
  - job_name: cage-crewai-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          component: crewai
          __path__: /var/log/cage/crewai/crewai.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            component: component
            message: message
            file: file
            line: line
      - labels:
          level:
          component:
          file:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
          action_on_failure: fudge
      - output:
          source: message

  # Management logs
  - job_name: cage-manage-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          component: manage
          __path__: /var/log/cage/manage.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            file: file
            line: line
            status: status
            date: date
      - labels:
          level:
          file:
          status:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
          action_on_failure: fudge
      - output:
          source: message

  # MCP logs
  - job_name: cage-mcp-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          component: mcp
          __path__: /var/log/cage/mcp/mcp.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            file: file
            line: line
            service: service
            event: event
            method: method
            url: url
            path: path
            status_code: status_code
            duration_ms: duration_ms
            client_ip: client_ip
      - labels:
          level:
          file:
          service:
          event:
          method:
          status_code:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05,000'
          action_on_failure: fudge
      - output:
          source: message
