server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # Files API logs (JSONL format)
  - job_name: cage-files-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: files-api
          __path__: /var/log/cage/files-api/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
      - labels:
          level:
          service:
          route:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # Git API logs (JSONL format)
  - job_name: cage-git-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: git-api
          __path__: /var/log/cage/git-api/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
      - labels:
          level:
          service:
          route:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # RAG API logs (JSONL format)
  - job_name: cage-rag-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: rag-api
          __path__: /var/log/cage/rag-api/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
      - labels:
          level:
          service:
          route:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # Lock API logs (JSONL format)
  - job_name: cage-lock-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: lock-api
          __path__: /var/log/cage/lock-api/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
      - labels:
          level:
          service:
          route:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # Crew API logs (JSONL format)
  - job_name: cage-crew-api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: crew-api
          __path__: /var/log/cage/crew-api/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
      - labels:
          level:
          service:
          route:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # MCP Server logs (JSONL format)
  - job_name: cage-mcp-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: mcp
          __path__: /var/log/cage/mcp/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            tool: tool
            actor: actor
            status: status
      - labels:
          level:
          service:
          route:
          tool:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # CrewAI logs (JSONL format)
  - job_name: cage-crewai-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: crewai
          __path__: /var/log/cage/crewai/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
            component: component
      - labels:
          level:
          service:
          route:
          component:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg

  # Files operation logs (JSONL format)
  - job_name: cage-files-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cage-logs
          service: files
          __path__: /var/log/cage/files/**/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            level: level
            service: service
            request_id: request_id
            route: route
            msg: msg
            error: error
            file: file
            line: line
            func: func
            component: component
      - labels:
          level:
          service:
          route:
          component:
      - timestamp:
          source: ts
          format: "2006-01-02T15:04:05.000Z"
          action_on_failure: fudge
      - output:
          source: msg
